### ISSUE TITLE
ImportError: cannot import name 'METRO' from 'metro.modeling.bert.modeling_bstro'

### ISSUE THREAD

**Issue by JiahongWu1995** [paulchhuang/bstro#1]
hi, I am very interesting in your excellenct work! but i found there is a bug in the code when i run the demo code. https://github.com/paulchhuang/bstro/blob/main/docs/DEMO.md#human-scene-contact-detection.
ImportError: cannot import name 'METRO' from 'metro.modeling.bert.modeling_bstro'

**Comment by paulchhuang** [comment]
Thanks for giving the code a try. We have committed a fix. Please pull the latest code. 
There should be a METRO class in `metro/modeling/bert/modeling_bstro.py` now.

**Comment by JiahongWu1995** [comment]
thank you for your reply！
