### ISSUE TITLE
How to get config (.yaml) file for training?

### ISSUE THREAD

**Issue by hygenie1228** [paulchhuang/bstro#10]
Hi,
I'm currently following EXP.md instruction for the traininig.

According the training instruction, file `rich_for_bstro_tsv_db/train.yaml` is necessary to run.
https://github.com/paulchhuang/bstro/blob/main/scripts/training.sh#L13

How can I get this file?
Thank you.

**Comment by paulchhuang** [comment]
Hi, 
Have you downloaded the tsv databases from the RICH website, as described in the 1st step in EXP.md ? 
<img width="978" alt="image" src="https://github.com/paulchhuang/bstro/assets/10480537/f76b017e-0e4f-403f-8720-88bf1d40c812">

Once downloaded and unzipped, you'll see those yaml files.
