### ISSUE TITLE
Getting random output

### ISSUE THREAD

**Issue by charisoudis** [paulchhuang/bstro#11]
Hi and thanks for publishing the code of this great work!

I am getting the following weird output from a 3DPW frame:
![image](https://github.com/paulchhuang/bstro/assets/16089638/7b93b6f7-b01d-4140-a974-712a22c12568)

Seeing the contact probs, it seems that most are between [0.4, 0.55], so it is like a pseudo-random prediction.
I am following your code for loading the model, and preparing the input.

Do you think that this is related to the **checkpoint loading** of the BSTRO model (I used the `metro_3dpw_state_dict.bin`)?

Best,
Thanos

**Comment by paulchhuang** [comment]
Hi, 
If you are following the instructions here: https://github.com/paulchhuang/bstro/blob/main/docs/DEMO.md#human-scene-contact-detection, you should load the `hsi_hrnet_3dpw_b32_checkpoint_15.bin` downloaded from the RICH website ( hyperlink "BSTRO pre-trained checkpoint"), not `metro_3dpw_state_dict.bin`.
`metro_3dpw_state_dict.bin` is from another work METRO, which estimates joint positions, not contact. Two models share the same HRNet backbones so we used `metro_3dpw_state_dict.bin` to initialize its weight _during training_, but for inference you need only `hsi_hrnet_3dpw_b32_checkpoint_15.bin` if my memory serves me correctly.

**Comment by charisoudis** [comment]
That's right, thanks for the response. I got that fixed now!

**Comment by jyuntins** [comment]
Hi @charisoudis, I am trying to run BSTRO, but it seems that the download link of metro models provided by the author is unavailable or expired. Is it possible that you can share the files to me?    

1. models/metro_release/metro_3dpw_state_dict.bin
2. models/hrnet/hrnetv2_w64_imagenet_pretrained.pth
3. models/hrnet/hrnetv2_w40_imagenet_pretrained.pth
4. models/hrnet/cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml
5. models/hrnet/cls_hrnet_w40_sgd_lr5e-2_wd1e-4_bs32_x100.yaml

I would greatly appreciate if you can help!

**Comment by soddday** [comment]
Hi,@jyuntins,I also need this file models/hrnet/hrnetv2_w40_imagenet_pretrained.pth and I failed to download it in many ways, can you share it to me?
