### ISSUE TITLE
Missing hsc labels for sequence "Gym_012_lunge2" in test set

### ISSUE THREAD

**Issue by xymsh** [paulchhuang/bstro#4]
The "Gym_012_lunge2" folder is missing in "test_hsc".

**Comment by paulchhuang** [comment]
Hi! Thanks for pointing this out. Gym_012_lunge2 is added in the test_hsc.zip. Please follow the new instructions on the website where users can choose to download everything again (including Gym_012_lunge2) or just for Gym_012_lunge2. Note that not only hsc labels but the SMPL-X params of Gym_012_lunge2 are updated.

Meanwhile, there will be a new repo. called "RICH_toolkit" coming soon. In the future please post dataset-related questions there and keep here for just BSTRO. Thanks!

**Comment by paulchhuang** [comment]
@xymsh May I ask if you had successfully downloaded "ParkingLot2_017_pushup1" in the testset earlier? It's the last sequence in the script. The link was broken so I wonder if you encountered any issue. If so, we made a quick fix so feel free to try the last line again.

**Comment by xymsh** [comment]
Thank you for telling me. I didn't download the videos before because the file is so large and not enough space is available on my hpc. It would be appreciated if you could provide a low-resolution version.
