### ISSUE TITLE
Empty file in RICH dataset

### ISSUE THREAD

**Issue by xymsh** [paulchhuang/bstro#9]
There is something wrong with the download link on the website [rich](https://rich.is.tue.mpg.de/download.php) for the images in JPEG formats of the validation set. The downloaded file is empty.

**Comment by leoisufa** [comment]
same question

**Comment by paulchhuang** [comment]
Thanks for reporting this. We just made a quick fix. Can you try again?

**Comment by xymsh** [comment]
It's all good now. Thanks.
